### ISSUE TITLE
[BUG] Chewing up 100% of the CPU time

### ISSUE THREAD

**Issue by PySimpleGUI** [Ecolistico/GrowGreens#37]
**Describe the bug**

The program is taking ALL available CPU cycles on the core it is running on.  This will starve all processes that happen to be running on that same core.

**To Reproduce**

Run gui.py

**Expected behavior**

A lot less CPU used.

**Screenshots**

![image](https://user-images.githubusercontent.com/46163555/80659942-5b324e00-8a58-11ea-824a-652f43673b47.png)

**Desktop (please complete the following information):**

Windows 10

**Additional context**

Because you're running with a timeout value of zero, something warned against many times in the documentation, your program will use all available time.  If you look at the screenshot you'll see core 8 has 100% usage. The middle part of the graph is when I changed the value to 20, which means your loop runs every 20 milliseconds, still a very fast refresh time.  By making it 20, you see the amount of time that was used was only 20% or less of the total on that core.

With today's computers you don't notice these things easily because it "feels" like your system is running fine. But it's not all OK as you are taking away from other system programs.  I highly recommend putting something other than zero.

**Comment by jmcasimar** [comment]
You are right, we create a gui class with the idea to integrate this interface in the rest of the code. When I run the code from [main.py](https://github.com/Ecolistico/GrowGreens/blob/master/Python/Master/growMaster.py) I does not have this problem since we add timouts about 200 miliseconds that are not related with the GUI.

However, running the GUI program directly consumes all available CPU. I am going to add a timeout variable to check if the program is running from the main.py or gui.py to adjust the timeout correctly.

**Comment by jmcasimar** [comment]
This issue was solved in 46a063ae2f5a1139492a00eabf658ae957ba5d08
